

Import("H:\fansub-work\[fansub-dev\LogoDraw\LogoDraw.avsi")

BlankClip()

Subtitle(VersionString())

LogoDraw("Feather.png", align=9)
LogoDraw("Feather.png", x=0.6, y=0.65, align=5, opacity=0.43, start=20, end_margin=50, fadein=10, fadeout=10, zoom=2.0)
          
LogoDraw("Feather.png", x=0.5, y=0.5, align=5, opacity=0.43, start=10, end=100, fadein=10, fadeout=10)

LogoDraw("Feather.png", x=0.3, y=0.3, align=5, opacity=0.43, start=30, end=-50, fadein=10, fadeout=10)
